# Typos configuration
# https://github.com/crate-ci/typos

[files]
# Exclude reference Python source (contains minified JS with false positives)
extend-exclude = ["reference/"]

[default.extend-words]
# HSA = Apple's authentication system term (Hardware Security Authentication)
hsa = "hsa"
